version: '3.9'

networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created

services:
  selenoid:
    networks:
      selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./work/selenoid/video:/opt/selenoid/video"
      - "./work/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    ports:
      - "4444:4444"

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - "./work/jenkins:/var/jenkins_home"
    networks:
      - selenoid
    ports:
      - "8000:8080"
